import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScroll from '../components/SmoothScroll/index'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aye - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <link rel="icon" href="/favicon.ico"  />

      <body className={inter.className}>
        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
